gantt
    title CSci Software Engineering Project
    dateFormat  YYYY-MM-DD
    axisFormat  %m-%d

    section Section 1
    Task 1           :a1, 2025-02-19, 5d
    Task 2           :after a1, 3d

    section Section 2
    Task 3           :2025-02-24, 4d
    Task 4           :after a2, 2d

    section Section 3
    Task 5           :2025-02-28, 6d
    Task 6           :2025-03-06, 3d
